Commit #0.0.12
заменил на -march=armv7-a

Добавил .sh для arm8v

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,3 +61,61 @@ jobs:
         with:
           name: ne10-benchmark-logs-armv7
           path: bin/qemu_bench_armv7_*.log
+
+
+
+  build-armv8:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Make build scripts executable
+        run: chmod +x scripts/*.sh
+
+      - name: Install cross-compile tools and QEMU for ARMv8
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y \
+            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
+            gcc-arm-linux-gnueabi g++-arm-linux-gnueabi \
+          cmake git make \
+          qemu-user qemu-user-static
+    
+      - name: Verify qemu-aarch64 installation
+        run: qemu-aarch64 --version
+
+      - name: Copy ne10_bench.c to scripts
+        run: cp ne10_bench.c scripts/
+
+      - name: Build ARMv8-A (hard float)
+        run: echo "1" | scripts/ne10_build_armv8a_hard.sh
+
+      # - name: Build ARMv7-A (soft float)
+      #   run: echo "2" | scripts/ne10_build_armv7a_hard.sh
+
+      - name: List files in bin
+        run: ls -la bin/
+
+      - name: Run ARMv8 hard float benchmark in QEMU
+        run: |
+          qemu-aarch64 -L /usr/aarch64-linux-gnu bin/ne10_armv8a_hard_float $ITERATIONS \
+            > bin/qemu_bench_armv8_hard.log 2>&1 || echo "QEMU returned error, but continuing"
+
+      # - name: Run ARMv7 soft float benchmark in QEMU
+      #   run: |
+      #     qemu-arm -L /usr/arm-linux-gnueabi bin/ne10_armv7a_soft_float $ITERATIONS \
+      #       > bin/qemu_bench_armv7_soft.log 2>&1 || echo "QEMU returned error, but continuing"
+
+      - name: Upload ARMv8 binaries
+        uses: actions/upload-artifact@v4
+        with:
+          name: ne10-binaries-armv8
+          path: bin/ne10_armv8a_*
+
+      - name: Upload ARMv8 QEMU logs
+        uses: actions/upload-artifact@v4
+        with:
+          name: ne10-benchmark-logs-armv8
+          path: bin/qemu_bench_armv8_*.log
+
+
