Commit #0.0.8
запустил .sh на linux, упростил до hard float - работает.
добавил в .с ne10_fft_c2c_1d_float32_neon().
убрал soft float из yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,8 +34,8 @@ jobs:
       - name: Build ARMv7-A (hard float)
         run: echo "1" | scripts/ne10_build_armv7a_soft_hard.sh
 
-      - name: Build ARMv7-A (soft float)
-        run: echo "2" | scripts/ne10_build_armv7a_soft_hard.sh
+      # - name: Build ARMv7-A (soft float)
+      #   run: echo "2" | scripts/ne10_build_armv7a_soft_hard.sh
 
       - name: List files in bin
         run: ls -la bin/
@@ -45,10 +45,10 @@ jobs:
           qemu-arm -L /usr/arm-linux-gnueabihf bin/ne10_bench_ne10_armv7a_hard_float $ITERATIONS \
             > bin/qemu_bench_armv7_hard.log 2>&1 || echo "QEMU returned error, but continuing"
 
-      - name: Run ARMv7 soft float benchmark in QEMU
-        run: |
-          qemu-arm -L /usr/arm-linux-gnueabi bin/ne10_bench_ne10_armv7a_soft_float $ITERATIONS \
-            > bin/qemu_bench_armv7_soft.log 2>&1 || echo "QEMU returned error, but continuing"
+      # - name: Run ARMv7 soft float benchmark in QEMU
+      #   run: |
+      #     qemu-arm -L /usr/arm-linux-gnueabi bin/ne10_bench_ne10_armv7a_soft_float $ITERATIONS \
+      #       > bin/qemu_bench_armv7_soft.log 2>&1 || echo "QEMU returned error, but continuing"
 
       - name: Upload ARMv7 binaries
         uses: actions/upload-artifact@v4
